config/routes.rb
Rails.application.routes.draw do
  
  get 'about' => 'welcome#about'

  get 'music' => 'welcome#music'

  get 'webdesign' => 'welcome#webdesign'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />


<!-- Latest compiled and minified JavaScript -->
<%#= javascript_include_tag  "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %> 

  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar-wrapper">
  <div class="container">
    <div class="navbar navbar-inverse navbar-static-top">
      
        <div class="navbar-header">
	    <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </a>
        <a class="navbar-brand" href="#">Malahki Mack</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Music", music_path %></li>
            <li><%= link_to "Web design", webdesign_path %></li>
            <!-- <li><a href="#contact">Register</a></li> -->
          </ul>
        </div>
    </div>
  </div><!-- /container -->
</div><!-- /navbar wrapper -->


<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<html>
<body>
	<div class="pages">

	<h2>You have to learn the rules of the game. 
		And then you have to play better than anyone else.</h2>


	<h4> -Albert Einstein- </h4>
	</div>

	<div class="pages" id="placer">
	

	<div class="col-md-4">

	<div class="panel-body center-it">

	<h4>Fake text for placement</h4>
</div>
</div>

	<div class="col-md-4">

	<div class="panel-body center-it">
  		<%= image_tag "Mmackpic.jpg", size: "450x400", alt: "travelpic" %>
	
  	</div>
	</div>	
	</div>

	<!-- place a dark gray transparent container around the origin text -->

</body>
</html>

app/views/welcome/index.html.erb
<div class="pages">
	<h1>Music|Media|Life</h1>
</div>	

<div class="pages">
	<h2>Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it.</h2>	

	<h4> -Bruce Lee, Founder of Jeet Kune Do- </h4> 
</div>

    
<!-- Warming Up -->
<link href='http://fonts.googleapis.com/css?family=Buenard:700' rel='stylesheet' type='text/css'>
<script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script>

<!--Video Section-->
<section class="content-section video-section">
  <div class="pattern-overlay">
  <a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=kiJGKTml_oU',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</a>
    <div class="container">
      <div class="row">
        <div class="col-lg-12" id="mover">
        <h1>Malahki</h1>  
        <h2></h2>
	   </div>
      </div>
    </div>
  </div>
</section>
<!--Video Section Ends Here-->

<script>
$(document).ready(function () {
$(".player").mb_YTPlayer();
});
</script>

app/views/welcome/music.html.erb
<html>
<body>
	<div class="pages">
	<h1>Beats by M.Mack</h1>
	<h3>My All</h3>
	<%= audio_tag("My All by M.Mack(unofficial).mp3", autoplay: false, controls: true) =%>
	</div>

<!-- Javascrpt portion -->

<!-- Javascrpt portion -->

	<div class="pages">
	<h1>Compositions</h1>
	<h4></h4>
	
	<iframe width="560" height="315" src="https://www.youtube.com/embed/252HQxsQrv4" frameborder="0" allowfullscreen></iframe>

	<iframe width="560" height="315" src="https://www.youtube.com/embed/k50sOuXCygk" frameborder="0" allowfullscreen></iframe>


	<iframe width="560" height="315" src="https://www.youtube.com/embed/mbOij2xl_UU" frameborder="0" allowfullscreen></iframe>

	<iframe width="560" height="315" src="https://www.youtube.com/embed/as6j5QoSFko" frameborder="0" allowfullscreen></iframe>

	</div>
	<!-- <div>
	<h1>Videos</h1>
	<h4> Place list of my youtube vids here! </h4>
	</div> -->
</body>
</html>

app/views/welcome/webdesign.html.erb
<html>
<body>
	<div class="pages">
	<h1>Webpages</h1>
	<h4> links to ROR sites </h4>
	</div>
	
</body>
</html>